name: Caller One

on: workflow_dispatch
# on:
#   pull_request:
#     types: [closed]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      target: stage
      service-name: serverless

  finish:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - run: echo "Caller One - finished running reusable workflow"
