name: Caller One

on:
  push:
    branches:
      - stage

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml@stage
    with:
      target: stage
      service-name: serverless-stage
    secrets: inherit

  finish:
    runs-on: ubuntu-latest
    needs: call-reusable
    steps:
      - run: echo "Caller One - finished running reusable workflow"
